CREATE TABLE cooking_log(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    menu_Kind VARCHAR(255),
    score INTEGER,
    recipe VARCHAR(1000),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET = utf8mb4;
